name: forcing-timeseries
channels:
  - conda-forge
  - chrisroadmap
dependencies:
  - climateforcing>=0.3.0
  - h5py
  - fair==2.1.4
  - iris
  - jupyter
  - matplotlib
  - nbstripout
  - netcdf4
  - numpy
  - pandas
  - pooch
  - scipy
  - tqdm
