name: forcing-timeseries
channels:
  - conda-forge
  - chrisroadmap
dependencies:
  - climateforcing>=0.3.0
  - h5py
  - fair==2.2.2
  - iris
  - jupyter
  - jupytext
  - matplotlib
  - nco
  - netcdf4
  - numpy
  - pandas
  - pooch
  - scipy
  - tqdm
